### ISSUE TITLE
Output folder creation fails when video title has invalid characters

### ISSUE THREAD

**Issue by Xerol** [bjsi/youtube-dl-split-chapters#1]
Running on windows 10 through powershell. One problematic video ID: vy8thOCA4to - this title has forward slashes in it which are not valid as part of a folder name.

Attempted to workaround by specifying an output filename for the download, but it still tries to create a folder based upon the video title. Using --restrict-filenames also did not help.

**Comment by SupaaSchnitzel** [comment]
I had the same problem and if its needed for a hotfix you can change line 87 in main.py and use something different from fulltitle or you can put a method in that filters out invalid chars from the title and use it in the same line.

**Comment by bjsi** [comment]
Sorry for the late reply! I just added some code to use the sanitize_filename method from youtube dl. And you should be able to use the --restrict-filenames option if you need it.

**Comment by bjsi** [comment]
Ok there was still an issue apparently (#5) because I didn't sanitize the filenames and paths correctly. I think I fixed it properly now with the latest commit.
