### ISSUE TITLE
How do I set a bitrate? 

### ISSUE THREAD

**Issue by HASJ** [bjsi/youtube-dl-split-chapters#2]
FFmpeg is defaulting to 96kb/s and that's lower than even YouTube's best audio rates.

https://www.youtube.com/watch?v=_-LZudHEk7k Video in question.

**Comment by bjsi** [comment]
I'm not sure, this repo is just a thin wrapper around youtube-dl so you should just be able to pass whatever bitrate options youtube-dl requires. Perhaps this SO post will help: https://stackoverflow.com/questions/34930699/cant-use-youtube-dl-to-download-specified-bitrate.
