### ISSUE TITLE
Remove platform-specific characters from file name

### ISSUE THREAD

**Issue by ghost** [bjsi/youtube-dl-split-chapters#5]
First of all this is a fantastic project, thank you - and keep it up.

**Describe the bug**
If you try to download a video with platform-specific characters in the chapters name (like` \, /, ?, *, :, `etc.) the file simply won't saved, or saves the content to an alternate data stream.

**To Reproduce**
The first chapter won't downloaded on Windows.
Run `main.py -x -f "bestaudio/best" "https://www.youtube.com/watch?v=oKE7OlR0ysw"` for example.

Even worse if the video has `:` in it the chapter name (saves to an ADS).
Run `main.py -x -f "bestaudio/best" "https://www.youtube.com/watch?v=t76npIZoxvY"` for example.

**Technical informations**
-OS: Windows 10 20H2 hu-HU
-Python: 3.9 (64 bit)
-youtube-dl version: 2021.06.06

**Suggested solution**

Add some search-replace stuff to line 74, into `main.py` .

    def output_chapter_file(self, chapter: str):
        basename = chapter.replace("/", "-") + self.extension    
        return os.path.join(self.output_folder, basename)

This hotfix solved the `/` sign's problem ,but since I'm not fluent in Python I can't add the other signs (therefore I didn't created a PR). [Here](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions) you can find a complete list about the reserved characters.

**Comment by bjsi** [comment]
Ah I thought I solved this with an earlier commit, but looks like I didn't sanitize the path properly. Should be fixed now with the latest commit. Let me know if there are any more issues!
